import 'dart:math' as math;
import 'package:flutter/material.dart';
enum JarvisVisualState { idle, listening, thinking, speaking, confirmation, error, exiting }
class JarvisReactor extends StatefulWidget{const JarvisReactor({super.key,this.color=const Color(0xFF37D5EE),this.state=JarvisVisualState.idle});final Color color;final JarvisVisualState state;@override State<JarvisReactor>createState()=>_JarvisReactorState();}
class _JarvisReactorState extends State<JarvisReactor>with SingleTickerProviderStateMixin{late final AnimationController _c=AnimationController(vsync:this,duration:const Duration(seconds:14))..repeat();@override void dispose(){_c.dispose();super.dispose();}@override Widget build(BuildContext c)=>RepaintBoundary(child:CustomPaint(painter:_P(_c,widget.color,widget.state),size:Size.infinite));}
class _N{_N(this.x,this.y,this.z,this.p);final double x,y,z,p;}
class _P extends CustomPainter{_P(this.time,this.color,this.state):super(repaint:time);final Animation<double>time;final Color color;final JarvisVisualState state;static final List<_N>nodes=List.generate(150,(i){final g=math.pi*(3-math.sqrt(5)),y=1-2*(i+.5)/150,r=math.sqrt(math.max(0,1-y*y)),a=g*i;return _N(math.cos(a)*r,y,math.sin(a)*r,i*.73);});double get intensity=>switch(state){JarvisVisualState.idle=>.72,JarvisVisualState.listening=>1.05,JarvisVisualState.thinking=>1.22,JarvisVisualState.speaking=>1.42,JarvisVisualState.confirmation=>1.6,JarvisVisualState.error=>1.2,JarvisVisualState.exiting=>.3};
@override void paint(Canvas c,Size s){final o=s.center(Offset.zero),r=s.shortestSide*.43,t=time.value*math.pi*2,sp=state==JarvisVisualState.thinking?1.8:state==JarvisVisualState.speaking?1.35:state==JarvisVisualState.listening?1.1:.6,rot=t*sp*.32;final pts=<Offset>[],dep=<double>[];c.drawCircle(o,r*1.18,Paint()..shader=RadialGradient(colors:[color.withValues(alpha:.20*intensity),color.withValues(alpha:.05),Colors.transparent]).createShader(Rect.fromCircle(center:o,radius:r*1.18)));
for(final n in nodes){final x=n.x*math.cos(rot)-n.z*math.sin(rot),z=n.x*math.sin(rot)+n.z*math.cos(rot),y=n.y*math.cos(rot*.55)-z*math.sin(rot*.55),zz=n.y*math.sin(rot*.55)+z*math.cos(rot*.55),p=1/(1.55-zz*.38);pts.add(Offset(o.dx+x*r*p,o.dy-y*r*p));dep.add(zz);}final edge=Paint()..style=PaintingStyle.stroke..strokeWidth=.55..color=color.withValues(alpha:.10*intensity);for(var i=0;i<nodes.length;i++){for(var j=i+1;j<nodes.length;j++){final dx=pts[i].dx-pts[j].dx,dy=pts[i].dy-pts[j].dy;if(dx*dx+dy*dy<(r*.19)*(r*.19)&&((dep[i]+dep[j])/2)>-.55)c.drawLine(pts[i],pts[j],edge);}}final order=List.generate(nodes.length,(i)=>i)..sort((a,b)=>dep[a].compareTo(dep[b]));for(final i in order){final pulse=.5+.5*math.sin(t*(state==JarvisVisualState.speaking?5:2)+nodes[i].p),sz=(1.1+2.1*math.max(0,dep[i]+.25))*(.8+.35*pulse)*intensity;c.drawCircle(pts[i],sz,Paint()..color=color.withValues(alpha:(.35+.55*math.max(0,dep[i]+.3))*intensity.clamp(0,1)));}final cp=1+.055*math.sin(t*1.6);c.drawCircle(o,r*.16*cp,Paint()..shader=RadialGradient(colors:[Colors.white.withValues(alpha:.95),color.withValues(alpha:.8),color.withValues(alpha:.08),Colors.transparent],stops:const[0,.2,.62,1]).createShader(Rect.fromCircle(center:o,radius:r*.18)));
final ring=Paint()..style=PaintingStyle.stroke..strokeWidth=1.2..color=color.withValues(alpha:.22*intensity);c.drawOval(Rect.fromCenter(center:o,width:r*2.15,height:r*.72),ring);c.save();c.translate(o.dx,o.dy);c.rotate(-rot*.8);c.translate(-o.dx,-o.dy);c.drawOval(Rect.fromCenter(center:o,width:r*1.55,height:r*.52),ring);c.restore();if(state==JarvisVisualState.listening){final q=.5+.5*math.sin(t*3);c.drawCircle(o,r*(.9+.08*q),Paint()..style=PaintingStyle.stroke..strokeWidth=2..color=color.withValues(alpha:.35+.35*q));}if(state==JarvisVisualState.error){final x=Paint()..color=Colors.redAccent.withValues(alpha:.9)..strokeWidth=3;c.drawLine(o.translate(-r*.12,-r*.12),o.translate(r*.12,r*.12),x);c.drawLine(o.translate(r*.12,-r*.12),o.translate(-r*.12,r*.12),x);}}
@override bool shouldRepaint(_P old)=>old.color!=color||old.state!=state;}
